version: '3.8'
networks:
  global-network:
    external: true
  rescue-network:
    external: true
services:
  rescue-webhook:
    container_name: rescue-webhook
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VERIFY_TOKEN=${VERIFY_TOKEN}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - PHONE_NUMBER_ID=${PHONE_NUMBER_ID}
      - VERSION=${VERSION}
      - BASE_URL=${BASE_URL}
      - DEBUG=${DEBUG}
      - REDIS_URL=redis://redis:6379/0
      - WEBSOCKET_URL=${WEBSOCKET_URL}
      - WEBHOOK_PORT=5050
      - CACHE_DB_PATH=${CACHE_DB_PATH}
      - CACHE_CLEANUP_INTERVAL=${CACHE_CLEANUP_INTERVAL}
      - BULK_MAX_WORKERS=${BULK_MAX_WORKERS}
      - WHATSAPP_QUEUE_NAME=${WHATSAPP_QUEUE_NAME:-whatsapp_queue}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    ports:
      - "5050:5050"
    volumes:
      - sqlite_data:/app/data
    networks:
      global-network:
        aliases:
          - rescue-webhook
      rescue-network:
        aliases:
          - rescue-webhook
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
  worker:
    container_name: rescue-worker
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - VERIFY_TOKEN=${VERIFY_TOKEN}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - PHONE_NUMBER_ID=${PHONE_NUMBER_ID}
      - VERSION=${VERSION}
      - BASE_URL=${BASE_URL}
      - DEBUG=${DEBUG}
      - REDIS_URL=redis://redis:6379/0
      - CACHE_DB_PATH=${CACHE_DB_PATH}
      - CACHE_CLEANUP_INTERVAL=${CACHE_CLEANUP_INTERVAL}
      - BULK_MAX_WORKERS=${BULK_MAX_WORKERS}
      - WHATSAPP_QUEUE_NAME=${WHATSAPP_QUEUE_NAME:-whatsapp_queue}
    volumes:
      - sqlite_data:/app/data
    networks:
      global-network:
        aliases:
          - rescue-worker
    restart: unless-stopped
volumes:
  sqlite_data:
    driver: local
  redis_data:
    external: true
