name: Deploy Webhook

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: deploy-production
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            set -e
            cd "${{ secrets.DEPLOY_PATH }}"
            git fetch --prune
            git reset --hard origin/main
            docker network inspect global-network >/dev/null 2>&1 || docker network create global-network
            docker network inspect rescue-network >/dev/null 2>&1 || docker network create rescue-network
            docker volume inspect redis_data >/dev/null 2>&1 || docker volume create redis_data
            docker-compose pull
            docker-compose up -d --remove-orphans rescue-webhook worker
